# Generated by Django 2.2.6 on 2020-06-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WinningNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WB1', models.IntegerField()),
                ('WB2', models.IntegerField()),
                ('WB3', models.IntegerField()),
                ('WB4', models.IntegerField()),
                ('WB5', models.IntegerField()),
                ('RB', models.IntegerField()),
                ('DD', models.DateField()),
            ],
        ),
    ]
