# Generated by Django 2.2.6 on 2020-06-02 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WB1', models.IntegerField()),
                ('WB2', models.IntegerField()),
                ('WB3', models.IntegerField()),
                ('WB4', models.IntegerField()),
                ('WB5', models.IntegerField()),
                ('RB', models.IntegerField()),
                ('DD', models.DateField()),
                ('users', models.ManyToManyField(related_name='ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
